### ISSUE TITLE
Change #reg_name0, #reg_name1, #reg_name2, ... to Array of #regname

### ISSUE THREAD

**Issue by f-bro** [embed-rs/embedded_stm32f7#1]
For example in nvic.rs:
```
pub iser0: volatile::ReadWrite<Iser0>,
pub iser1: volatile::ReadWrite<Iser1>,
pub iser2: volatile::ReadWrite<Iser2>,
```
could be changed to:
```
pub iser: [volatile::ReadWrite<Iser>; 3],
```

What is the best way to implement this? Just edit the nvic.rs file in this repo or change it in the svd_codgen project (with if p.name == "NVIC" then ...)?

**Comment by phil-opp** [comment]
I think we already modified the generated code, so just editing `nvic.rs` should be fine.

**Comment by f-bro** [comment]
Ok 👍

**Comment by f-bro** [comment]
I'm a little bit confused with the number of registers.

The reference manuel says:
```
up to 98 maskable interrupt channels for STM32F75xxx and STM32F74xxx
``` 
but for example we have only 3 interrupt set enable registers (each of 32 bits).

In total we only can enable 3 * 32 = 96 interrupts.
Is there a mistake in the svd file or do I have an error in reasoning?

The Nvic itself supports up to 240 interrupts and has 8 interrupt set enable registers.

**Comment by f-bro** [comment]
I checked the STM32F7x.svd file and there are only iser0, iser1 and iser2.
